{{- if eq .Values.kubeflow.profile.from "user" }}
apiVersion: redhatcop.redhat.io/v1alpha1
kind: UserConfig
metadata:
  name: kubeflow-profile
spec:
  annotationSelector: {}
  identityExtraFieldSelector: {}
  labelSelector: {}
  providerName: my_htpasswd_provider
  templates:
  - objectTemplate: |
      apiVersion: kubeflow.org/v1beta1
      kind: Profile
      metadata:
        name: {{ printf "{{ .Name }}" }}
      spec:
        owner:
          kind: User
          name: {{ printf "{{ .Name }}" }}
        resourceQuotaSpec:
          hard:
            cpu: "8"
            memory: 16Gi
            "requests.nvidia.com/gpu": "10"
            persistentvolumeclaims: "10"
            requests.storage: "200Gi"
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: kubeflow-editor
        namespace: {{ printf "{{ .Name }}" }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: kubeflow-edit
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ printf "{{ .Name }}" }} 
  - objectTemplate: | 
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: {{ printf "{{ .Name }}" }}-sm-view
        namespace: {{ .Values.control_plane.namespace }}
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: ClusterRole
        name: view
      subjects:
      - kind: User
        apiGroup: rbac.authorization.k8s.io
        name: {{ printf "{{ .Name }}" }}
{{- end }}
